- name: configuring the mongodb server
  become: yes
  hosts: mongodb
  tasks:
  - name: copying mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: install mongodb server
    ansible.builtin.dnf:
      name: mongodb-org 
      state: present
    
  - name : start and enable service
    ansible.builtin.service:
      name: mongodb
      enabled: yes
      state: started
